import {
  mdiAccountCircle,
  mdiMonitor,
    mdiBookInformationVariant,
    mdiAccountBadge,
    mdiAccountGroup,
    mdiCog,
  mdiGithub,
  mdiLock,
  mdiAlertCircle,
  mdiSquareEditOutline,
  mdiTable,
  mdiViewList,
  mdiTelevisionGuide,
  mdiResponsive,
  mdiPalette,
  mdiReact,
} from "@mdi/js";

export default [
  {
    to: "/dashboard",
    icon: mdiMonitor,
    label: "Dashboard",
    adminRoute: false,
  },
  {
    to: "/authors",
    label: "Authors",
    icon: mdiAccountBadge,
    adminRoute: true,
  },
  {
    to: "/books",
    label: "Books",
    icon: mdiBookInformationVariant,
    adminRoute: false,
  },
  {
    to: "/categories",
    label: "Categories",
    icon: mdiCog,
    adminRoute: true,
  },
  {
    to: "/reservations",
    label: "Reservations",
    icon: mdiViewList,
    adminRoute: true,
  },
  {
    to: "/users",
    label: "Users",
    icon: mdiAccountGroup,
    adminRoute: true,
  },
  {
    to: "/login",
    label: "Login",
    icon: mdiLock,
    adminRoute: false,
  },
  {
    to: "/profile",
    label: "Profile",
    icon: mdiAccountCircle,
    adminRoute: false,
  },
  {
    to: "/forms",
    label: "Forms",
    icon: mdiSquareEditOutline,
    adminRoute: false,
  },
];
