Author:
    type: object
    config:
        description: 'Author'
        fields:
            id:
                type: 'Int!'
                description: 'The unique ID of the author'
            name:
                type: 'String!'
                description: 'Name of the author'

Authors:
    type: object
    config:
        description: 'Authors'
        fields:
            authors:
                type: '[Author]'
                description: 'Author details'

AuthorInput:
    type: input-object
    config:
        fields:
            name:
                type: 'String!'
                validation:
                    - Length:
                          min: 3
                          max: 255
                description: 'Author name'
