CategoryList:
    type: object
    config:
        description: 'Category list'
        fields:
            categories:
                type: '[Category]'
                description: 'Category details'
