Mutation:
    type: object
    config:
        fields:
            createCategory:
                args:
                    category:
                        type: 'CategoryInput!'
                        validation: cascade
                description: Mutation to create new category
                type: 'CategoryMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\CreateCategoryMutation", args, validator)'
            updateCategory:
                args:
                    id:
                        type: 'Int!'
                    category:
                        type: 'CategoryInput!'
                        validation: cascade
                description: Mutation to update a category
                type: 'CategoryMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\UpdateCategoryMutation", args, validator)'
            deleteCategory:
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete category
                type: 'CategoryMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\DeleteCategoryMutation", args)'
            createAuthor:
                args:
                    author:
                        type: 'AuthorInput!'
                        validation: cascade
                description: Mutation to create new author
                type: 'AuthorMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\CreateAuthorMutation", args, validator)'
            deleteAuthor:
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete author
                type: 'AuthorMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\DeleteAuthorMutation", args)'
