Mutation:
    type: object
    config:
        fields:
            createCategory:
                args:
                    category:
                        type: 'CreateCategoryInput!'
                        validation: cascade
                description: Mutation to create new category
                type: 'CategoryMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\CreateCategoryMutation", args, validator)'
            deleteCategory:
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete category
                type: 'CategoryMutationResponse!'
                resolve: '@=mutation("App\\Mutation\\DeleteCategoryMutation", args)'
