Query:
    type: object
    config:
        description: 'Category ORM repository'
        fields:
            category:
                type: 'Category'
                args:
                    id:
                        description: 'Resolves using the category ID.'
                        type: 'Int'
                resolve: '@=resolver("App\\Resolver\\CategoryResolver", [args])'
