Query:
    type: object
    config:
        description: 'ORM repository'
        fields:
            getCategory:
                type: 'Category'
                args:
                    id:
                        description: 'Gets category by ID'
                        type: 'Int'
                resolve: '@=resolver("App\\Resolver\\CategoryResolver", [args])'
            getCategoryList:
                type: 'CategoryList'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("App\\Resolver\\CategoryListResolver", [args])'
            getAuthor:
                type: 'Author'
                args:
                    id:
                        description: 'Gets author by ID'
                        type: 'Int'
                resolve: '@=resolver("App\\Resolver\\AuthorResolver", [args])'
            getAuthorList:
                type: 'AuthorList'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("App\\Resolver\\AuthorListResolver", [args])'
