Reservation:
    type: object
    config:
        description: 'Reservation'
        fields:
            id:
                type: 'Int!'
                description: 'The unique ID of the reservation'
            book:
                type: 'Book!'
                description: 'Book'
            user:
                type: 'User!'
                description: 'User'
            dateFrom:
                type: 'String!'
                description: 'Reservation date from'
            dateTo:
                type: 'String!'
                description: 'Reservation date to'

Reservations:
    type: object
    config:
        description: 'Reservations'
        fields:
            reservations:
                type: '[Reservation]'
                description: 'Reservation details'

ReservationInput:
    type: input-object
    config:
        fields:
            bookId:
                type: 'Int!'
                description: 'Book'
            userId:
                type: 'Int!'
                description: 'User'
            dateFrom:
                type: 'String!'
                description: 'Reservation date from'
                validation:
                    - NotBlank:
                    - DateTime:
                          format: 'Y-m-d H:i'
            dateTo:
                type: 'String!'
                description: 'Reservation date to'
                validation:
                    - NotBlank:
                    - DateTime:
                          format: 'Y-m-d H:i'
