RootMutation:
    type: object
    config:
        fields:
            createCategory:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    category:
                        type: 'CategoryInput!'
                        validation: cascade
                description: Mutation to create new category
                type: 'MutationResponse!'
                resolve: '@=mutation("createCategory", args, validator)'
            updateCategory:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                    category:
                        type: 'CategoryInput!'
                        validation: cascade
                description: Mutation to update a category
                type: 'MutationResponse!'
                resolve: '@=mutation("updateCategory", args, validator)'
            deleteCategory:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete category
                type: 'MutationResponse!'
                resolve: '@=mutation("deleteCategory", args)'
            createAuthor:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    author:
                        type: 'AuthorInput!'
                        validation: cascade
                description: Mutation to create new author
                type: 'MutationResponse!'
                resolve: '@=mutation("createAuthor", args, validator)'
            updateAuthor:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                    author:
                        type: 'AuthorInput!'
                        validation: cascade
                description: Mutation to update a author
                type: 'MutationResponse!'
                resolve: '@=mutation("updateAuthor", args, validator)'
            deleteAuthor:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete author
                type: 'MutationResponse!'
                resolve: '@=mutation("deleteAuthor", args)'
            createUser:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    user:
                        type: 'UserInput!'
                        validation: cascade
                description: Mutation to create new user
                type: 'MutationResponse!'
                resolve: '@=mutation("createUser", args, validator)'
            updateUser:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                    user:
                        type: 'UserInput!'
                        validation: cascade
                description: Mutation to update a user
                type: 'MutationResponse!'
                resolve: '@=mutation("updateUser", args, validator)'
            deleteUser:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete user
                type: 'MutationResponse!'
                resolve: '@=mutation("deleteUser", args)'
            createBook:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    book:
                        type: 'BookInput!'
                        validation: cascade
                description: Mutation to create new book
                type: 'MutationResponse!'
                resolve: '@=mutation("createBook", args, validator)'
            updateBook:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                    book:
                        type: 'BookInput!'
                        validation: cascade
                description: Mutation to update a book
                type: 'MutationResponse!'
                resolve: '@=mutation("updateBook", args, validator)'
            deleteBook:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete book
                type: 'MutationResponse!'
                resolve: '@=mutation("deleteBook", args)'
            createReservation:
                args:
                    reservation:
                        type: 'ReservationInput!'
                        validation: cascade
                description: Mutation to create new reservation
                type: 'MutationResponse!'
                resolve: '@=mutation("createReservation", args, validator)'
            updateReservation:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                    reservation:
                        type: 'ReservationInput!'
                        validation: cascade
                description: Mutation to update a reservation
                type: 'MutationResponse!'
                resolve: '@=mutation("updateReservation", args, validator)'
            deleteReservation:
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        type: 'Int!'
                description: Mutation to delete reservation
                type: 'MutationResponse!'
                resolve: '@=mutation("deleteReservation", args)'

MutationResponse:
    type: object
    config:
        builders:
            - builder: MutationResponse
