RootQuery:
    type: object
    config:
        description: 'ORM repository'
        fields:
            getCategory:
                type: 'Category'
                args:
                    id:
                        description: 'Gets category by ID'
                        type: 'Int'
                resolve: '@=resolver("getCategory", [args])'
            getCategories:
                type: 'Categories'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getCategories", [args])'
            getAuthor:
                type: 'Author'
                args:
                    id:
                        description: 'Gets author by ID'
                        type: 'Int'
                resolve: '@=resolver("getAuthor", [args])'
            getAuthors:
                type: 'Authors'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getAuthors", [args])'
            getUser:
                type: 'User'
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        description: 'Gets user by ID'
                        type: 'Int'
                resolve: '@=resolver("getUser", [args])'
            getUserByUsername:
                type: 'User'
                args:
                    username:
                        description: 'Gets user by username'
                        type: 'String'
                resolve: '@=resolver("getUserByUsername", [args])'
            getUsers:
                type: 'Users'
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getUsers", [args])'
            getBook:
                type: 'Book'
                args:
                    id:
                        description: 'Gets book by ID'
                        type: 'Int'
                resolve: '@=resolver("getBook", [args])'
            getBooks:
                type: 'Books'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getBooks", [args])'
            getReservation:
                type: 'Reservation'
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    id:
                        description: 'Gets reservation by ID'
                        type: 'Int'
                resolve: '@=resolver("getReservation", [args])'
            getReservations:
                type: 'Reservations'
                access: '@=hasRole("ROLE_ADMIN")'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getReservations", [args])'
            getMyReservations:
                type: 'Reservations'
                args:
                    userId:
                        description: 'User ID'
                        type: 'Int'
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getMyReservations", [args])'
