RootQuery:
    type: object
    config:
        description: 'ORM repository'
        fields:
            getCategory:
                type: 'Category'
                args:
                    id:
                        description: 'Gets category by ID'
                        type: 'Int'
                resolve: '@=resolver("getCategory", [args])'
            getCategories:
                type: 'Categories'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getCategories", [args])'
            getAuthor:
                type: 'Author'
                args:
                    id:
                        description: 'Gets author by ID'
                        type: 'Int'
                resolve: '@=resolver("getAuthor", [args])'
            getAuthors:
                type: 'Authors'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getAuthors", [args])'
            getUsers:
                type: 'Users'
                args:
                    limit:
                        description: 'Limit'
                        type: 'Int'
                    orderBy:
                        description: 'Order by field'
                        type: 'String'
                    criteria:
                        description: 'Order criteria'
                        type: 'String'
                resolve: '@=resolver("getUsers", [args])'
