User:
    type: object
    config:
        description: 'User'
        fields:
            id:
                type: 'Int!'
                description: 'The unique ID of the user'
            name:
                type: 'String!'
                description: 'Name of the user'
            username:
                type: 'String!'
                description: 'Username of the user'
            email:
                type: 'String!'
                description: 'Email of the user'
            status:
                type: 'String!'
                description: 'User status - either active or blocked'
            roles:
                type: '[String]!'
                description: 'User roles - either ROLE_ADMIN, ROLE_USER or both'

Users:
    type: object
    config:
        description: 'Users'
        fields:
            users:
                type: '[User]'
                description: 'User details'

UserInput:
    type: input-object
    config:
        fields:
            name:
                type: 'String!'
                validation:
                    - Length:
                          min: 3
                          max: 255
                description: 'Full name'
            username:
                type: 'String!'
                validation:
                    - Length:
                          min: 3
                          max: 255
                description: 'Username'
            email:
                type: 'String!'
                validation:
                    - Length:
                          min: 3
                          max: 255
                description: 'Email'
            status:
                type: 'String!'
                validation:
                    - Length:
                          min: 3
                          max: 255
                description: 'Status'
            roles:
                type: '[String]!'
                description: 'Roles'
