on: [push]
jobs:
  lint:
      container: php:8.2.3-fpm-alpine
      runs-on: php-latest
      steps:
          - run: cd api
          - run: curl --show-error --silent "https://getcomposer.org/installer" | php
          - run: apk add yamllint
          - run: php composer.phar install --prefer-dist --no-autoloader --no-scripts --no-progress
          - run: php composer.phar clear-cache
          - run: vendor/bin/phpstan --ansi --memory-limit=2G
          - run: vendor/bin/ecs --ansi
          - run: yamllint .
          - run: bin/console lint:yaml config src
          - run: bin/console lint:container
